create table MOCK_DATA (
	employee_id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	date_of_birth DATE,
	department VARCHAR(9),
	salary DECIMAL(8,2),
	hire_date DATE,
	manager_id INT,
	job_title VARCHAR(50)
);
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (1, 'Alphonse', 'Keymer', 'akeymer0@booking.com', '6/10/1993', 'Sales', 90398.95, '3/17/2021', 1, 'Senior Editor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (2, 'Nelli', 'Yarnton', 'nyarnton1@theatlantic.com', '9/11/1977', 'Finance', 115623.45, '11/21/2013', 2, 'Systems Administrator III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (3, 'Camille', 'Ions', 'cions2@geocities.jp', '1/18/1973', 'IT', 32826.27, '11/6/2021', 3, 'Structural Analysis Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (4, 'Cloe', 'Trimme', 'ctrimme3@liveinternet.ru', '3/25/1988', 'Marketing', 95006.77, '12/14/2012', 4, 'VP Accounting');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (5, 'Adan', 'Whitehall', 'awhitehall4@wix.com', '10/18/1983', 'Finance', 34736.11, '2/14/2014', 5, 'Project Manager');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (6, 'Orion', 'McCullum', 'omccullum5@hud.gov', '7/20/1999', 'IT', 69124.52, '10/26/2018', 6, 'Social Worker');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (7, 'Rena', 'Anderbrugge', 'randerbrugge6@nba.com', '4/15/1976', 'Finance', 85730.31, '4/19/2019', 7, 'Professor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (8, 'Dix', 'Coxall', 'dcoxall7@twitpic.com', '1/7/1987', 'Sales', 46141.64, '8/10/2019', 8, 'Research Associate');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (9, 'Zondra', 'Tunmore', 'ztunmore8@t-online.de', '10/17/1965', 'HR', 136510.94, '3/22/2017', 9, 'VP Marketing');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (10, 'Belva', 'Coarser', 'bcoarser9@t-online.de', '10/14/1965', 'Finance', 88492.71, '5/19/2014', 10, 'Administrative Assistant III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (11, 'Doris', 'Lebang', 'dlebanga@tripadvisor.com', '7/10/1975', 'IT', 55519.78, '10/29/2021', 11, 'Desktop Support Technician');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (12, 'Christoffer', 'Stares', 'cstaresb@surveymonkey.com', '8/30/1999', 'Finance', 59960.27, '2/11/2016', 12, 'Financial Advisor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (13, 'Charmane', 'Haines', 'chainesc@abc.net.au', '9/18/1972', 'HR', 113020.77, '11/6/2010', 13, 'Human Resources Assistant III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (14, 'Cart', 'Pitcaithley', 'cpitcaithleyd@fda.gov', '11/17/1968', 'HR', 103601.12, '12/7/2021', 14, 'Social Worker');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (15, 'Chase', 'Prydie', 'cprydiee@github.io', '11/13/1987', 'IT', 138126.54, '12/2/2017', 15, 'Legal Assistant');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (16, 'Millisent', 'Sutton', 'msuttonf@webnode.com', '6/4/1983', 'Finance', 66796.83, '4/23/2020', 16, 'Environmental Tech');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (17, 'Mallory', 'Hendrichs', 'mhendrichsg@reference.com', '8/16/1962', 'IT', 84119.78, '12/21/2013', 17, 'Environmental Specialist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (18, 'Belvia', 'Stirgess', 'bstirgessh@foxnews.com', '12/3/1992', 'Marketing', 31116.31, '11/13/2016', 18, 'Compensation Analyst');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (19, 'Josey', 'Adamik', 'jadamiki@mtv.com', '3/8/1994', 'Finance', 135761.11, '1/22/2018', 19, 'Nuclear Power Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (20, 'Chelsea', 'McDirmid', 'cmcdirmidj@joomla.org', '6/3/1996', 'IT', 122782.6, '8/24/2014', 20, 'Registered Nurse');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (21, 'Marne', 'Carbert', 'mcarbertk@nsw.gov.au', '5/24/1966', 'Sales', 60823.81, '5/7/2021', 21, 'Geological Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (22, 'Brook', 'Foard', 'bfoardl@blogspot.com', '8/14/1999', 'Sales', 31332.5, '10/25/2017', 22, 'Staff Scientist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (23, 'Job', 'Bunston', 'jbunstonm@bigcartel.com', '10/22/1975', 'HR', 110916.52, '1/17/2021', 23, 'Community Outreach Specialist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (24, 'Bay', 'Benoist', 'bbenoistn@slideshare.net', '8/3/1970', 'Sales', 76423.52, '6/28/2013', 24, 'Administrative Officer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (25, 'Glynda', 'Sedworth', 'gsedwortho@pcworld.com', '8/21/1972', 'IT', 64961.13, '4/15/2010', 25, 'Quality Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (26, 'Valentino', 'Stansbie', 'vstansbiep@npr.org', '3/25/1968', 'Finance', 107807.13, '10/7/2017', 26, 'Civil Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (27, 'Roxanna', 'Skahill', 'rskahillq@latimes.com', '9/26/1995', 'Marketing', 119436.17, '5/3/2017', 27, 'Sales Associate');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (28, 'Pen', 'Spratt', 'psprattr@friendfeed.com', '12/18/1972', 'HR', 101700.19, '1/2/2011', 28, 'Data Coordinator');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (29, 'Ashia', 'Phippin', 'aphippins@addthis.com', '11/1/1975', 'Marketing', 149429.5, '2/17/2017', 29, 'Statistician IV');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (30, 'Consalve', 'Styche', 'cstychet@a8.net', '4/28/1995', 'HR', 130919.17, '10/21/2016', 30, 'Help Desk Technician');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (31, 'Salomi', 'Kempshall', 'skempshallu@amazon.co.jp', '12/15/1994', 'Sales', 80815.62, '4/30/2016', 31, 'Paralegal');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (32, 'Cosmo', 'Force', 'cforcev@ucoz.com', '12/11/1997', 'HR', 119523.28, '4/25/2017', 32, 'Chief Design Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (33, 'Cathe', 'Rudsdale', 'crudsdalew@furl.net', '12/1/1973', 'Marketing', 133045.1, '5/11/2013', 33, 'Director of Sales');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (34, 'Gennie', 'Quested', 'gquestedx@drupal.org', '3/28/1999', 'Finance', 80040.48, '5/19/2016', 34, 'Web Developer III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (35, 'Cassandre', 'Bahls', 'cbahlsy@cloudflare.com', '5/5/1981', 'HR', 141558.02, '5/31/2021', 35, 'Accounting Assistant I');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (36, 'Worth', 'Putton', 'wputtonz@hatena.ne.jp', '9/6/1990', 'Sales', 75934.77, '3/24/2017', 36, 'Programmer Analyst III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (37, 'Judas', 'Chauvey', 'jchauvey10@apple.com', '10/19/1977', 'HR', 102536.64, '11/29/2020', 37, 'GIS Technical Architect');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (38, 'Ardath', 'Iddon', 'aiddon11@spotify.com', '1/4/1995', 'Sales', 60357.26, '1/6/2018', 38, 'Internal Auditor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (39, 'Lethia', 'Guillem', 'lguillem12@cnet.com', '3/28/1962', 'IT', 111252.4, '12/13/2020', 39, 'Internal Auditor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (40, 'Klara', 'Hawkswood', 'khawkswood13@typepad.com', '3/16/1963', 'Marketing', 99495.86, '7/24/2021', 40, 'Recruiting Manager');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (41, 'Merridie', 'Muckian', 'mmuckian14@nytimes.com', '1/4/1990', 'HR', 149800.3, '8/19/2014', 41, 'Quality Control Specialist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (42, 'Tiffanie', 'Bowick', 'tbowick15@vk.com', '10/16/1982', 'Marketing', 149725.39, '7/2/2021', 42, 'VP Marketing');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (43, 'Micheil', 'Di Pietro', 'mdipietro16@cisco.com', '2/2/1971', 'Marketing', 103028.39, '11/19/2010', 43, 'Media Manager III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (44, 'Arnold', 'Maseres', 'amaseres17@ovh.net', '4/27/1975', 'Sales', 78001.2, '2/18/2010', 44, 'Nurse Practicioner');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (45, 'Issiah', 'Hembling', 'ihembling18@nyu.edu', '1/26/1962', 'IT', 139685.22, '7/9/2018', 45, 'Payment Adjustment Coordinator');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (46, 'Audre', 'Rountree', 'arountree19@nyu.edu', '4/3/1987', 'Finance', 47400.87, '8/30/2019', 46, 'Programmer Analyst II');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (47, 'Donielle', 'MacAskie', 'dmacaskie1a@google.cn', '1/14/1997', 'Marketing', 115256.43, '5/12/2015', 47, 'Electrical Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (48, 'Jennie', 'Rodden', 'jrodden1b@phoca.cz', '3/23/1982', 'Finance', 41190.55, '5/4/2018', 48, 'Chief Design Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (49, 'Jefferey', 'Church', 'jchurch1c@dedecms.com', '2/15/1961', 'Marketing', 40381.11, '6/8/2011', 49, 'Chief Design Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (50, 'Lewie', 'Cinelli', 'lcinelli1d@washington.edu', '12/4/1967', 'IT', 118927.79, '3/19/2020', 50, 'Automation Specialist I');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (51, 'Carmon', 'Grayham', 'cgrayham1e@mtv.com', '10/30/1964', 'IT', 147479.49, '1/10/2010', 51, 'GIS Technical Architect');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (52, 'Claus', 'Musker', 'cmusker1f@infoseek.co.jp', '10/20/1962', 'Sales', 98148.26, '9/12/2013', 52, 'Health Coach I');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (53, 'Adaline', 'Hallas', 'ahallas1g@tmall.com', '1/18/1991', 'Finance', 42813.01, '4/12/2021', 53, 'Environmental Tech');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (54, 'Stanwood', 'Gosselin', 'sgosselin1h@hud.gov', '7/26/1976', 'Sales', 68604.71, '2/14/2019', 54, 'Marketing Assistant');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (55, 'Pancho', 'Mephan', 'pmephan1i@nationalgeographic.com', '9/1/1995', 'Marketing', 141381.01, '5/19/2010', 55, 'Database Administrator I');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (56, 'Wright', 'Sends', 'wsends1j@example.com', '12/1/1996', 'Marketing', 143894.79, '2/29/2016', 56, 'Geological Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (57, 'Barnie', 'Whitters', 'bwhitters1k@google.com.au', '11/26/1976', 'IT', 129832.16, '5/9/2019', 57, 'Information Systems Manager');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (58, 'Gannon', 'Dalston', 'gdalston1l@walmart.com', '2/9/1966', 'IT', 99223.99, '12/13/2016', 58, 'Community Outreach Specialist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (59, 'Alyda', 'Boreland', 'aboreland1m@java.com', '12/11/1972', 'Finance', 112685.78, '12/16/2011', 59, 'Statistician IV');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (60, 'Indira', 'Hamblington', 'ihamblington1n@usa.gov', '9/24/1974', 'Sales', 74380.34, '3/13/2016', 60, 'Electrical Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (61, 'Rosemary', 'Finders', 'rfinders1o@bloomberg.com', '2/2/1984', 'Finance', 119094.27, '4/15/2021', 61, 'Speech Pathologist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (62, 'Bertie', 'Leinster', 'bleinster1p@seattletimes.com', '9/26/1974', 'Marketing', 137495.76, '1/16/2015', 62, 'Mechanical Systems Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (63, 'Rosetta', 'Stigers', 'rstigers1q@is.gd', '12/16/1961', 'Marketing', 148904.1, '12/23/2019', 63, 'Engineer IV');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (64, 'Eachelle', 'Jaram', 'ejaram1r@sphinn.com', '4/29/1988', 'Sales', 129212.63, '2/25/2021', 64, 'Automation Specialist II');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (65, 'Allayne', 'Gillise', 'agillise1s@drupal.org', '4/26/1998', 'HR', 87240.25, '7/4/2020', 65, 'Recruiter');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (66, 'Marven', 'Keedwell', 'mkeedwell1t@xrea.com', '3/22/1989', 'HR', 60845.07, '4/25/2017', 66, 'Geologist IV');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (67, 'Irvine', 'Castanho', 'icastanho1u@canalblog.com', '9/24/1997', 'Sales', 91037.79, '10/2/2016', 67, 'Geologist IV');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (68, 'Caril', 'Cartmale', 'ccartmale1v@amazon.co.jp', '4/28/1983', 'HR', 44086.76, '4/10/2013', 68, 'Accounting Assistant III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (69, 'Myrtia', 'Tompkinson', 'mtompkinson1w@smugmug.com', '9/4/1984', 'Sales', 53782.92, '2/2/2020', 69, 'Internal Auditor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (70, 'Rhea', 'Filshin', 'rfilshin1x@g.co', '5/7/1972', 'Finance', 103696.0, '4/10/2012', 70, 'Senior Sales Associate');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (71, 'Rhodia', 'Easby', 'reasby1y@opera.com', '9/25/1960', 'Finance', 149599.6, '1/15/2012', 71, 'Junior Executive');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (72, 'Fenelia', 'Keyden', 'fkeyden1z@loc.gov', '5/26/1985', 'Sales', 139878.32, '4/17/2011', 72, 'VP Product Management');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (73, 'Clarissa', 'Boone', 'cboone20@shinystat.com', '11/10/1982', 'HR', 34111.35, '4/29/2020', 73, 'Research Associate');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (74, 'Bruce', 'Offener', 'boffener21@privacy.gov.au', '4/4/1961', 'Marketing', 127756.53, '4/6/2010', 74, 'Assistant Professor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (75, 'Rivalee', 'Elvins', 'relvins22@stanford.edu', '8/6/1992', 'Marketing', 117457.26, '7/11/2014', 75, 'Programmer II');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (76, 'Roslyn', 'Reiach', 'rreiach23@qq.com', '8/25/1980', 'IT', 127941.17, '9/23/2013', 76, 'Environmental Tech');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (77, 'Ode', 'Arnald', 'oarnald24@ucla.edu', '7/19/1980', 'Finance', 42370.91, '3/15/2018', 77, 'Occupational Therapist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (78, 'Nicole', 'Youster', 'nyouster25@cpanel.net', '1/18/1963', 'HR', 70270.13, '10/5/2021', 78, 'Health Coach III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (79, 'Norry', 'Mabone', 'nmabone26@ifeng.com', '8/14/1970', 'Marketing', 74520.61, '6/18/2013', 79, 'Product Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (80, 'Martina', 'Greedier', 'mgreedier27@ask.com', '1/18/1985', 'Sales', 41146.08, '10/30/2012', 80, 'Web Developer III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (81, 'Mirelle', 'Bednell', 'mbednell28@gov.uk', '11/24/1990', 'Sales', 110903.57, '2/4/2021', 81, 'Data Coordinator');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (82, 'Fonzie', 'Radeliffe', 'fradeliffe29@macromedia.com', '1/26/1973', 'HR', 102691.13, '7/1/2015', 82, 'Associate Professor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (83, 'Clara', 'Smallshaw', 'csmallshaw2a@stumbleupon.com', '2/24/1972', 'IT', 122163.05, '9/17/2015', 83, 'Executive Secretary');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (84, 'Noell', 'Pyson', 'npyson2b@cbsnews.com', '10/21/1982', 'IT', 118823.97, '7/7/2014', 84, 'Pharmacist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (85, 'Allegra', 'Sleford', 'asleford2c@addtoany.com', '5/2/1985', 'Finance', 129850.61, '10/10/2021', 85, 'Registered Nurse');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (86, 'Allayne', 'Paffitt', 'apaffitt2d@mozilla.com', '1/13/1977', 'IT', 41370.69, '10/19/2014', 86, 'Environmental Tech');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (87, 'Boris', 'Duetsche', 'bduetsche2e@opera.com', '5/12/1975', 'Marketing', 131812.71, '3/3/2010', 87, 'Human Resources Manager');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (88, 'Steffane', 'Allaway', 'sallaway2f@shareasale.com', '12/8/1986', 'Finance', 42762.96, '5/30/2019', 88, 'VP Marketing');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (89, 'Thaddus', 'Duddridge', 'tduddridge2g@webeden.co.uk', '3/28/1985', 'Sales', 83176.0, '8/26/2011', 89, 'Executive Secretary');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (90, 'Delaney', 'McCullock', 'dmccullock2h@cbslocal.com', '9/9/1961', 'Marketing', 89158.26, '9/7/2012', 90, 'Financial Advisor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (91, 'Ninon', 'Nicolson', 'nnicolson2i@vimeo.com', '6/27/1988', 'HR', 87755.74, '6/16/2020', 91, 'Actuary');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (92, 'Elisabetta', 'Squire', 'esquire2j@1688.com', '4/16/1988', 'Marketing', 84279.11, '4/15/2013', 92, 'Software Test Engineer IV');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (93, 'Parrnell', 'Elston', 'pelston2k@cyberchimps.com', '8/28/1988', 'Sales', 140300.26, '10/20/2012', 93, 'Programmer Analyst II');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (94, 'Shandee', 'Koubu', 'skoubu2l@seattletimes.com', '9/10/1985', 'Marketing', 45100.57, '2/18/2018', 94, 'VP Sales');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (95, 'Bourke', 'Althrope', 'balthrope2m@vistaprint.com', '1/15/1977', 'HR', 86244.29, '4/20/2020', 95, 'Research Associate');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (96, 'Heather', 'Rohlfs', 'hrohlfs2n@gizmodo.com', '11/23/1982', 'Finance', 51826.94, '10/24/2019', 96, 'Media Manager IV');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (97, 'Dulci', 'Shout', 'dshout2o@ycombinator.com', '10/9/1991', 'HR', 63333.49, '3/14/2021', 97, 'Legal Assistant');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (98, 'Fairleigh', 'Staziker', 'fstaziker2p@hao123.com', '2/21/1997', 'IT', 41189.06, '11/22/2012', 98, 'Data Coordinator');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (99, 'Durward', 'Deare', 'ddeare2q@ucsd.edu', '11/17/1988', 'IT', 56955.87, '3/23/2016', 99, 'Help Desk Technician');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (100, 'Raymond', 'Schreiner', 'rschreiner2r@timesonline.co.uk', '2/6/1983', 'Finance', 55117.67, '8/16/2011', 100, 'Librarian');
