create table MOCK_DATA (
	employee_id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	date_of_birth DATE,
	department VARCHAR(9),
	salary DECIMAL(8,2),
	hire_date DATE,
	manager_id INT,
	job_title VARCHAR(50)
);
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (1, 'Mary', 'Arnhold', 'marnhold0@jigsy.com', '2/7/1990', 'HR', 148848.64, '7/30/2010', 1, 'Developer IV');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (2, 'Emelda', 'Finan', 'efinan1@cam.ac.uk', '5/13/1987', 'HR', 135775.12, '8/22/2016', 2, 'Nurse');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (3, 'Crichton', 'Priestley', 'cpriestley2@youtube.com', '12/7/1981', 'IT', 145517.36, '4/26/2014', 3, 'Engineer II');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (4, 'Alli', 'Pierucci', 'apierucci3@illinois.edu', '2/8/1973', 'Finance', 146377.72, '9/5/2018', 4, 'Computer Systems Analyst III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (5, 'Holden', 'Killigrew', 'hkilligrew4@google.cn', '4/17/1963', 'HR', 96244.92, '7/4/2017', 5, 'Physical Therapy Assistant');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (6, 'Almira', 'Ennor', 'aennor5@fema.gov', '7/14/1965', 'IT', 67196.86, '12/7/2016', 6, 'Financial Analyst');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (7, 'Aindrea', 'Stripp', 'astripp6@comcast.net', '2/6/1968', 'Finance', 121626.79, '12/14/2018', 7, 'Administrative Officer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (8, 'Corney', 'Catterell', 'ccatterell7@domainmarket.com', '10/25/1961', 'Marketing', 77990.3, '9/26/2013', 8, 'Accountant I');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (9, 'Elfrida', 'Dohms', 'edohms8@mozilla.org', '8/11/1996', 'IT', 55638.07, '2/24/2018', 9, 'Associate Professor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (10, 'Jeffrey', 'Jedrzejkiewicz', 'jjedrzejkiewicz9@mlb.com', '2/21/1961', 'Sales', 93278.88, '1/20/2012', 10, 'Teacher');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (11, 'Allegra', 'Newitt', 'anewitta@yandex.ru', '10/27/1970', 'Sales', 86113.11, '11/9/2021', 11, 'Teacher');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (12, 'Sissie', 'Olliver', 'solliverb@apple.com', '9/26/1998', 'Marketing', 40762.73, '8/5/2017', 12, 'Senior Editor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (13, 'Padraic', 'Wilfinger', 'pwilfingerc@engadget.com', '5/16/1994', 'Finance', 128936.52, '11/26/2020', 13, 'Help Desk Operator');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (14, 'Kimberli', 'Pien', 'kpiend@diigo.com', '3/24/1967', 'Marketing', 102057.8, '4/17/2014', 14, 'Physical Therapy Assistant');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (15, 'Ambrosio', 'Parkisson', 'aparkissone@fotki.com', '12/20/1965', 'Finance', 148633.26, '3/17/2012', 15, 'Tax Accountant');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (16, 'Loralie', 'Whitney', 'lwhitneyf@dagondesign.com', '3/3/1970', 'HR', 30142.79, '5/24/2019', 16, 'Electrical Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (17, 'Micah', 'Hill', 'mhillg@myspace.com', '1/19/1994', 'HR', 89684.19, '9/3/2016', 17, 'Research Nurse');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (18, 'Langsdon', 'Beynon', 'lbeynonh@tripadvisor.com', '6/26/1989', 'Finance', 143322.38, '1/16/2014', 18, 'Analyst Programmer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (19, 'Kelly', 'Taylorson', 'ktaylorsoni@hugedomains.com', '2/15/1998', 'HR', 94767.45, '5/14/2016', 19, 'Account Executive');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (20, 'Christophorus', 'Folbigg', 'cfolbiggj@hatena.ne.jp', '11/15/1976', 'Marketing', 119375.88, '4/29/2017', 20, 'Assistant Media Planner');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (21, 'Alexei', 'Barfield', 'abarfieldk@ehow.com', '2/4/1964', 'Finance', 67681.2, '3/23/2015', 21, 'Product Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (22, 'Rosene', 'Deveraux', 'rdeverauxl@cocolog-nifty.com', '1/14/1968', 'IT', 36649.73, '6/9/2012', 22, 'Clinical Specialist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (23, 'Gaultiero', 'Van der Krui', 'gvanderkruim@va.gov', '3/18/1998', 'Sales', 116001.99, '4/8/2016', 23, 'Junior Executive');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (24, 'Birch', 'Wrigglesworth', 'bwrigglesworthn@whitehouse.gov', '8/27/1962', 'Sales', 67092.32, '6/16/2015', 24, 'Quality Control Specialist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (25, 'Larine', 'Churches', 'lchurcheso@cbslocal.com', '8/25/1964', 'IT', 51400.25, '2/13/2015', 25, 'VP Marketing');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (26, 'Franny', 'Dyneley', 'fdyneleyp@dropbox.com', '5/21/1976', 'Marketing', 31859.86, '1/11/2014', 26, 'GIS Technical Architect');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (27, 'Abe', 'Wilmott', 'awilmottq@cpanel.net', '2/28/1966', 'Sales', 96295.88, '12/1/2014', 27, 'Dental Hygienist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (28, 'Helena', 'Treske', 'htresker@webeden.co.uk', '6/27/1960', 'HR', 103708.59, '2/10/2016', 28, 'Dental Hygienist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (29, 'Prue', 'Madden', 'pmaddens@cnet.com', '8/23/1994', 'IT', 145505.8, '12/10/2013', 29, 'Design Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (30, 'Boycie', 'Oxberry', 'boxberryt@phpbb.com', '8/8/1960', 'Finance', 72399.62, '8/26/2015', 30, 'Project Manager');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (31, 'Morgan', 'Petrosian', 'mpetrosianu@wix.com', '10/21/1995', 'Marketing', 146743.48, '10/24/2013', 31, 'Graphic Designer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (32, 'Oralee', 'Newvell', 'onewvellv@nih.gov', '8/11/1962', 'HR', 116142.9, '11/24/2014', 32, 'Pharmacist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (33, 'Jacquelin', 'Luckcock', 'jluckcockw@tinypic.com', '3/10/1998', 'Finance', 140986.71, '1/12/2012', 33, 'Electrical Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (34, 'Emmit', 'Albrecht', 'ealbrechtx@shinystat.com', '3/21/1967', 'Marketing', 62222.86, '11/27/2020', 34, 'Account Coordinator');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (35, 'Cordy', 'Streat', 'cstreaty@instagram.com', '3/5/1997', 'Finance', 78716.02, '10/23/2013', 35, 'Registered Nurse');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (36, 'Jarrad', 'Clandillon', 'jclandillonz@rakuten.co.jp', '5/26/1985', 'Marketing', 99375.28, '7/10/2021', 36, 'Geological Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (37, 'Ulrika', 'Riccard', 'uriccard10@usnews.com', '5/27/1995', 'Marketing', 93206.85, '5/17/2013', 37, 'Account Coordinator');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (38, 'Mal', 'Phetteplace', 'mphetteplace11@state.tx.us', '2/17/1974', 'IT', 95221.76, '8/19/2014', 38, 'Research Assistant II');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (39, 'Murdock', 'Blondin', 'mblondin12@w3.org', '12/5/1969', 'Marketing', 36709.38, '11/1/2020', 39, 'Information Systems Manager');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (40, 'Yolane', 'Shillan', 'yshillan13@1und1.de', '10/17/1981', 'HR', 77277.63, '9/24/2020', 40, 'Nurse');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (41, 'Herculie', 'Lipscomb', 'hlipscomb14@webmd.com', '3/20/1962', 'IT', 117693.1, '5/25/2014', 41, 'Automation Specialist III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (42, 'Philis', 'Baldacchino', 'pbaldacchino15@mail.ru', '9/6/1986', 'IT', 86254.89, '10/23/2020', 42, 'Director of Sales');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (43, 'Aileen', 'Inder', 'ainder16@google.pl', '5/1/1972', 'Finance', 65464.04, '8/7/2021', 43, 'Account Coordinator');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (44, 'Tani', 'Rame', 'trame17@newyorker.com', '10/7/1996', 'Finance', 136488.34, '5/1/2012', 44, 'Financial Advisor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (45, 'Cassius', 'Volkers', 'cvolkers18@livejournal.com', '1/9/1983', 'Marketing', 72942.15, '7/11/2018', 45, 'Pharmacist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (46, 'Marya', 'Cunnington', 'mcunnington19@newyorker.com', '12/31/1973', 'Sales', 77604.79, '8/31/2010', 46, 'Paralegal');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (47, 'Saunderson', 'Ivanikhin', 'sivanikhin1a@comsenz.com', '10/7/1972', 'IT', 51888.26, '4/5/2017', 47, 'Computer Systems Analyst III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (48, 'Ripley', 'Jeeks', 'rjeeks1b@imageshack.us', '3/29/1963', 'HR', 67320.46, '4/18/2013', 48, 'Social Worker');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (49, 'Rodd', 'Halvosen', 'rhalvosen1c@google.fr', '1/15/1995', 'IT', 68385.06, '1/2/2011', 49, 'Nuclear Power Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (50, 'Kip', 'Brixham', 'kbrixham1d@qq.com', '7/21/1967', 'Sales', 42749.19, '7/5/2012', 50, 'Help Desk Technician');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (51, 'Sophey', 'Torrijos', 'storrijos1e@jalbum.net', '1/16/1966', 'Marketing', 133112.07, '11/18/2018', 51, 'Account Representative III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (52, 'Auguste', 'Dowzell', 'adowzell1f@narod.ru', '2/8/1995', 'HR', 83371.32, '12/11/2018', 52, 'Software Engineer III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (53, 'Anastassia', 'Feary', 'afeary1g@google.com.br', '8/16/1969', 'Finance', 138878.81, '10/30/2014', 53, 'Health Coach III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (54, 'Viole', 'Swaysland', 'vswaysland1h@infoseek.co.jp', '4/25/1982', 'Marketing', 91882.36, '8/29/2014', 54, 'Payment Adjustment Coordinator');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (55, 'Ashley', 'Briffett', 'abriffett1i@apple.com', '6/18/1985', 'Marketing', 60484.53, '3/9/2016', 55, 'Human Resources Manager');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (56, 'Georgianne', 'McAuliffe', 'gmcauliffe1j@forbes.com', '12/25/1992', 'IT', 71217.88, '10/29/2016', 56, 'Research Nurse');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (57, 'Ewart', 'Seaborn', 'eseaborn1k@unicef.org', '10/12/1972', 'Finance', 116531.84, '4/12/2017', 57, 'VP Product Management');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (58, 'Myrwyn', 'Phillip', 'mphillip1l@fotki.com', '8/29/1992', 'Finance', 62696.71, '9/12/2019', 58, 'Software Test Engineer II');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (59, 'Cordula', 'Keeffe', 'ckeeffe1m@usnews.com', '9/2/1987', 'Sales', 147542.43, '7/19/2014', 59, 'Actuary');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (60, 'Kermy', 'Santi', 'ksanti1n@blog.com', '4/24/1982', 'Finance', 30479.57, '9/21/2019', 60, 'Desktop Support Technician');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (61, 'Jeramie', 'Rickell', 'jrickell1o@wp.com', '10/12/1981', 'IT', 57359.24, '12/9/2014', 61, 'Senior Sales Associate');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (62, 'Morgun', 'Martino', 'mmartino1p@phoca.cz', '5/25/1976', 'Sales', 66225.03, '12/28/2020', 62, 'Programmer Analyst IV');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (63, 'Kinny', 'Brosini', 'kbrosini1q@wikia.com', '6/1/1985', 'Marketing', 89668.42, '5/2/2018', 63, 'Software Engineer II');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (64, 'Lorens', 'Jerdan', 'ljerdan1r@house.gov', '2/15/1989', 'Sales', 113423.98, '2/12/2020', 64, 'Media Manager II');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (65, 'Kelcy', 'Basill', 'kbasill1s@google.fr', '1/11/1998', 'IT', 74952.76, '7/23/2017', 65, 'Financial Advisor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (66, 'Geneva', 'Brenton', 'gbrenton1t@elegantthemes.com', '10/12/1976', 'Marketing', 146183.1, '12/17/2020', 66, 'Environmental Tech');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (67, 'Melloney', 'Mattschas', 'mmattschas1u@histats.com', '1/8/1967', 'HR', 111956.09, '11/6/2010', 67, 'Financial Analyst');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (68, 'Sheeree', 'Dyhouse', 'sdyhouse1v@ucla.edu', '8/3/1981', 'Marketing', 120411.09, '12/31/2016', 68, 'Financial Analyst');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (69, 'Barry', 'McGuane', 'bmcguane1w@ucoz.com', '12/20/1970', 'IT', 39084.5, '4/9/2018', 69, 'Technical Writer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (70, 'Sibylle', 'Spinetti', 'sspinetti1x@facebook.com', '4/14/1986', 'HR', 86482.03, '8/31/2018', 70, 'Human Resources Manager');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (71, 'Lynnett', 'Sherlaw', 'lsherlaw1y@washingtonpost.com', '4/8/1991', 'Marketing', 146537.48, '12/7/2021', 71, 'Administrative Assistant IV');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (72, 'Nealy', 'Knowlton', 'nknowlton1z@w3.org', '9/6/1981', 'Finance', 120166.56, '1/26/2015', 72, 'Professor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (73, 'Malvin', 'Lindenman', 'mlindenman20@last.fm', '4/24/1989', 'Sales', 132238.31, '6/9/2014', 73, 'Project Manager');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (74, 'Orlando', 'Pick', 'opick21@youtube.com', '12/9/1961', 'Finance', 42994.49, '7/25/2014', 74, 'Environmental Tech');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (75, 'Lana', 'Eager', 'leager22@cafepress.com', '2/4/1961', 'HR', 83751.08, '6/3/2013', 75, 'Software Consultant');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (76, 'Chase', 'Tomet', 'ctomet23@dropbox.com', '4/29/1994', 'HR', 148126.47, '1/19/2018', 76, 'Web Developer I');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (77, 'Vonnie', 'Ezzy', 'vezzy24@earthlink.net', '12/14/1982', 'Finance', 40286.29, '10/14/2010', 77, 'Structural Analysis Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (78, 'Alphonse', 'Bibey', 'abibey25@cocolog-nifty.com', '2/27/1976', 'Finance', 97086.96, '1/25/2018', 78, 'Community Outreach Specialist');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (79, 'Juliane', 'Wicklin', 'jwicklin26@ameblo.jp', '1/1/1990', 'IT', 55244.43, '4/27/2021', 79, 'Account Executive');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (80, 'Jerald', 'Caulket', 'jcaulket27@360.cn', '8/19/1986', 'HR', 147978.79, '4/23/2013', 80, 'Teacher');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (81, 'Eleni', 'Ivankov', 'eivankov28@who.int', '9/13/1990', 'Finance', 93052.22, '1/9/2014', 81, 'Accountant III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (82, 'Pearce', 'Toffts', 'ptoffts29@moonfruit.com', '12/30/1988', 'Sales', 64633.4, '2/21/2015', 82, 'Civil Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (83, 'Goldi', 'Vina', 'gvina2a@cpanel.net', '3/10/1963', 'Marketing', 49859.92, '2/13/2019', 83, 'Assistant Professor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (84, 'Brnaby', 'Barkshire', 'bbarkshire2b@surveymonkey.com', '11/14/1990', 'IT', 119569.44, '10/30/2019', 84, 'Professor');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (85, 'Agnola', 'Fawdry', 'afawdry2c@boston.com', '1/23/1987', 'IT', 31313.22, '2/13/2021', 85, 'Mechanical Systems Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (86, 'Lanette', 'Wehnerr', 'lwehnerr2d@wix.com', '7/16/1960', 'Finance', 101722.61, '3/15/2021', 86, 'Mechanical Systems Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (87, 'Tab', 'Glaisner', 'tglaisner2e@ed.gov', '10/8/1998', 'Marketing', 108906.07, '12/18/2017', 87, 'Nuclear Power Engineer');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (88, 'Bondy', 'Krysztofiak', 'bkrysztofiak2f@indiatimes.com', '10/6/1968', 'Sales', 54028.53, '7/15/2012', 88, 'Nurse Practicioner');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (89, 'Laura', 'Harme', 'lharme2g@harvard.edu', '5/4/1978', 'Finance', 65455.22, '3/22/2016', 89, 'Research Associate');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (90, 'Sharlene', 'McGrane', 'smcgrane2h@wired.com', '3/23/1967', 'IT', 86841.83, '11/24/2011', 90, 'Programmer IV');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (91, 'Jonis', 'Yule', 'jyule2i@oaic.gov.au', '8/5/1965', 'Marketing', 64760.97, '12/22/2017', 91, 'Recruiting Manager');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (92, 'Lauraine', 'Cancellor', 'lcancellor2j@blinklist.com', '1/6/1967', 'HR', 126838.77, '4/18/2016', 92, 'Human Resources Assistant IV');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (93, 'Renaldo', 'Booeln', 'rbooeln2k@discovery.com', '3/15/1973', 'IT', 75441.61, '5/10/2019', 93, 'Junior Executive');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (94, 'Fifine', 'Orys', 'forys2l@google.ca', '4/21/1975', 'Sales', 91217.09, '6/24/2021', 94, 'Office Assistant III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (95, 'Hoyt', 'Bonson', 'hbonson2m@simplemachines.org', '6/30/1964', 'Marketing', 62393.91, '3/4/2020', 95, 'Junior Executive');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (96, 'Malissia', 'Harral', 'mharral2n@va.gov', '7/15/1983', 'IT', 38247.83, '10/21/2017', 96, 'Health Coach II');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (97, 'Trudie', 'Brosnan', 'tbrosnan2o@blogger.com', '9/30/1982', 'HR', 113759.88, '7/1/2014', 97, 'Programmer Analyst III');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (98, 'Jarrett', 'Kenway', 'jkenway2p@exblog.jp', '6/16/1968', 'Sales', 62857.18, '4/4/2019', 98, 'Information Systems Manager');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (99, 'Risa', 'Treend', 'rtreend2q@dyndns.org', '6/26/1992', 'Sales', 80018.55, '1/30/2012', 99, 'VP Sales');
insert into MOCK_DATA (employee_id, first_name, last_name, email, date_of_birth, department, salary, hire_date, manager_id, job_title) values (100, 'Tallie', 'MacGhee', 'tmacghee2r@dyndns.org', '8/31/1984', 'IT', 69129.92, '5/30/2014', 100, 'Analog Circuit Design manager');

​
